[project]
name = "aws-cost-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.39.15",
    "twilio>=9.7.0",
]
